//=============================================================================
// Bare-metal main control program for SG AXI DMA + custom
// GF(2) matrix accelerator
//=============================================================================

#include "xparameters.h"
/*TODO: Generated by the platform/BSP from the Vivado hardware design.
This is the one tied directly to your hardware instance names, device IDs, base addresses, and parameter macros.*/

#include "xaxidma.h"
/*Provided by AMD/Xilinx standalone driver sources for AXI DMA.*/

#include "xil_cache.h"
/*Provided by the standalone BSP; it contains cache control APIs like flush/invalidate.*/

#include "xil_io.h"
/*Provided by the standalone BSP; used for low-level MMIO access such as Xil_In32 and Xil_Out32. AMD examples include it from the BSP rather than user code defining it.*/

#include "xil_printf.h"
/* Provided by the standalone BSP; it declares the lightweight xil_printf */

#include "xstatus.h"
/* XST_SUCCESS and XST_FAILURE are just 0 and 1, but using the macros
   makes the code more readable and consistent with Xilinx driver APIs.
   Provided by AMD/Xilinx common driver sources*/

#include "sleep.h"
/*Provided by the standalone environment/toolchain headers used by AMD bare-metal examples for calls like usleep().*/

#include "xuartps.h"
/*Provided by the standalone BSP; used here for PS UART host receive.*/

#include <string.h>

// The compiler adds it automatically when target is ARM 64-bit such as 64-bit A53.
#ifdef __aarch64__
#include "xil_mmu.h"
#endif


//=============================================================================
// Platform / Address Map
//=============================================================================
// TODO: Replace these with the real addresses from Vivado xparameters.h

//TODO: check xparameters.h to see if names are correct
#define DMA_DEV_ID           XPAR_AXIDMA_0_DEVICE_ID
#define DMA_BASEADDR         XPAR_XAXIDMA_0_BASEADDR

#define DDR_BASE_ADDR        0x10000000U   /* TODO: replace */
#define ACCEL_BASE_ADDR      0xA0000000U   /* TODO: replace AXI-Lite base */

#define TX_BD_SPACE_BASE     (DDR_BASE_ADDR + 0x00000000U)
#define TX_BD_SPACE_HIGH     (DDR_BASE_ADDR + 0x0001FFFFU)

#define RX_BD_SPACE_BASE     (DDR_BASE_ADDR + 0x00020000U)
#define RX_BD_SPACE_HIGH     (DDR_BASE_ADDR + 0x0003FFFFU)

//TODO: these are just example offsets for A, B, and C in DDR. Adjust as needed based on your memory map and alignment requirements. Make sure they are outside the BD spaces and properly aligned for cache line size if needed.
#define MATRIX_A_BASE        (DDR_BASE_ADDR + 0x00100000U)
#define MATRIX_B_BASE        (DDR_BASE_ADDR + 0x00200000U)
#define MATRIX_C_BASE        (DDR_BASE_ADDR + 0x00300000U)


//=============================================================================
// Accelerator Register Map
//=============================================================================
/* register offsets for control/status. Suggested meaning:

   CTRL    : bit 0 = start
   STATUS  : bit 0 = done, bit 1 = error
   M, K, N : matrix dimensions
   A_BYTES : total packed bytes streamed for A

   This interface is GF(2)-specific, no generic element-size register. */

#define ACCEL_REG_CTRL_OFFSET           0x00U
#define ACCEL_REG_STATUS_OFFSET         0x04U
#define ACCEL_REG_M_OFFSET              0x08U
#define ACCEL_REG_K_OFFSET              0x0CU
#define ACCEL_REG_N_OFFSET              0x10U
#define ACCEL_REG_A_BYTES_OFFSET        0x14U
#define ACCEL_REG_B_BYTES_OFFSET        0x18U
#define ACCEL_REG_C_BYTES_OFFSET        0x1CU

#define ACCEL_CTRL_START_MASK           0x00000001U

#define ACCEL_STATUS_DONE_MASK          0x00000001U
#define ACCEL_STATUS_ERROR_MASK         0x00000002U


//=============================================================================
// Matrix / DMA Job Parameters
//=============================================================================
/* GF(2) only.

   Storage in DDR is packed bit storage:
   - each byte holds 8 GF(2) elements
   - matrix byte counts are derived from bit counts

   For now:
   - matrix sizes are fixed at 256 x 256
   - A is M x K
   - B is K x N
   - C is M x N
   - descriptor payload length is 256 bytes
   - A and B are streamed sequentially on one TX path as two separate frames */

#define MATRIX_M              256U
#define MATRIX_K              256U
#define MATRIX_N              256U
#define BD_TRANSFER_LEN_BYTES 256U
#define POLL_TIMEOUT_COUNTER  1000000U

#define MATRIX_A_BITS     (MATRIX_M * MATRIX_K)
#define MATRIX_B_BITS     (MATRIX_K * MATRIX_N)
#define MATRIX_C_BITS     (MATRIX_M * MATRIX_N)

#define MATRIX_A_BYTES    ((MATRIX_A_BITS + 7U) / 8U)
#define MATRIX_B_BYTES    ((MATRIX_B_BITS + 7U) / 8U)
#define MATRIX_C_BYTES    ((MATRIX_C_BITS + 7U) / 8U)

// integer division but rounded up not down, for calculating descriptor counts
#define CEIL_DIV_U32(value, divisor) \
    (((value) + (divisor) - 1U) / (divisor))

#define TX_BD_COUNT_A        CEIL_DIV_U32(MATRIX_A_BYTES, BD_TRANSFER_LEN_BYTES)
#define TX_BD_COUNT_B        CEIL_DIV_U32(MATRIX_B_BYTES, BD_TRANSFER_LEN_BYTES)
#define TX_BD_COUNT_TOTAL    (TX_BD_COUNT_A + TX_BD_COUNT_B)

#define RX_BD_COUNT_C        CEIL_DIV_U32(MATRIX_C_BYTES, BD_TRANSFER_LEN_BYTES)


//=============================================================================
// UART / Host Packet Definitions
//=============================================================================
/* First host-load version:
   - fixed-size matrices
   - PS UART receive
   - little-endian 32-bit header fields
   - payload order: A bytes, then B bytes */

#define UART_DEV_ID          XPAR_XUARTPS_0_DEVICE_ID   /* TODO: replace if needed */
#define UART_BAUD_RATE       115200U
#define UART_RECV_TIMEOUT_COUNTER 10000000U
//TODO: 10s time out based on baudrate, is this too small?

#define HOST_TO_BOARD_MAGIC  0x4746324DU   /* "GF2M" */
#define HOST_PROTO_VERSION   1U

typedef struct {
    u32 Magic;
    u32 Version;
    u32 ABytes;
    u32 BBytes;
} user_HostToBoardHdr;

//=============================================================================
// Global DMA Instance
//=============================================================================
/* One global DMA driver object is enough for this bare-metal program. */
static XAxiDma AxiDma;
static XUartPs UartPs;

//=============================================================================
// Function Prototypes
//=============================================================================
/* The program is split into initialization, DDR preparation, descriptor submission,
   accelerator launch, completion polling, and cleanup. */

static int  user_DMA_Init(XAxiDma *AxiDmaPtr);
static int  user_Setup_Tx_Ring(XAxiDma *AxiDmaPtr);
static int  user_Setup_Rx_Ring(XAxiDma *AxiDmaPtr);

static int  user_UART_Init(void);
static int  user_UART_Recv_Exact(u8 *Dst, u32 Len);
static int  user_Load_Matrices_From_Host(void);

static void user_write_Matrices_To_DDR(void);
static void user_Flush_ABC_Buffers(void);
static void user_Invalidate_C_cache(void);

static int  user_Submit_Rx_Desc_For_C(XAxiDma *AxiDmaPtr);
static int  user_Submit_Tx_Desc_For_A_B(XAxiDma *AxiDmaPtr);

static void user_Program_Accelerator(void);
static void user_Start_Accelerator(void);
static int  user_Wait_For_Done(void);

static int  user_Drain_Completed_BDs(
    XAxiDma_BdRing *RingPtr,
    u32             ExpectedBdCount,
    const char     *RingName
);

static void user_Report_Completion(void);


//=============================================================================
// main()
//=============================================================================

int main(void) {

    int Status;
    //-----------------
    xil_printf("\r\n--- Accelerator main() start ---\r\n");

    #ifdef __aarch64__
        /* Descriptor memory is shared between CPU and DMA. Marking the BD spaces uncacheable
        avoids stale descriptor contents and stale descriptor status.
        TODO: 
        NORM_NONCACHE | INNER_SHAREABLE come from xil_mmu.h 
        They resolve to 0x701
        
        TODO: these both fall in the same area so one is redundant */
        Xil_SetTlbAttributes(TX_BD_SPACE_BASE, NORM_NONCACHE | INNER_SHAREABLE);
        Xil_SetTlbAttributes(RX_BD_SPACE_BASE, NORM_NONCACHE | INNER_SHAREABLE);
    #endif

    //=================================
    // initialize DMA
    //=================================
    Status = user_DMA_Init(&AxiDma);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("DMA init failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // setup TX ring
    //=================================
    Status = user_Setup_Tx_Ring(&AxiDma);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX ring setup failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // setup RX ring
    //================================= 
    Status = user_Setup_Rx_Ring(&AxiDma);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX ring setup failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // initialize UART
    //=================================
    Status = user_UART_Init();
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("UART init failed\r\n");
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // Load matrices to DDR
    //=================================
    // TODO: both uart and fixed matrix load are implemented for now;

    // user_write_Matrices_To_DDR();
    //-----------------
    Status = user_Load_Matrices_From_Host();
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("Matrix receive from host failed\r\n");
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // Flush A/B/C 
    //=================================
    /* Flush A/B after CPU writes. Also flush C after zeroing. */
    user_Flush_ABC_Buffers();
  

    //=================================
    // Submit RX descriptors for C
    //=================================
    /* RX must be posted before the accelerator starts producing C. */
    Status = user_Submit_Rx_Desc_For_C(&AxiDma);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX descriptor submission failed\r\n");
        //-----------------
        return XST_FAILURE;
    }
    

    //=================================
    // Submit TX descriptors for A and B
    //=================================
    /* TX is one sequential stream carrying two GF(2) frames: first A, then B. */
    Status = user_Submit_Tx_Desc_For_A_B(&AxiDma);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX descriptor submission failed\r\n");
        //-----------------
        return XST_FAILURE;
    }
    

    //=================================
    // Program accelerator
    //=================================
    user_Program_Accelerator();
    

    //=================================
    // Start accelerator
    //=================================
    user_Start_Accelerator();
    

    //=================================
    // poll for accelerator done
    //=================================
    // TODO: The accelerator is assumed to clear old status internally before next start. 
    Status = user_Wait_For_Done();
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("Accelerator reported failure or timeout\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // Drain completed descriptors and verify
    //=================================
    /* accelerator Might report done but software should still reclaim and free all
       completed BDs and verify completion/error flags. */
    Status = user_Drain_Completed_BDs(
        XAxiDma_GetTxRing(&AxiDma),
        TX_BD_COUNT_TOTAL,
        "TX"
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX completion drain failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // Drain completed descriptors and verify for RX
    //=================================
    Status = user_Drain_Completed_BDs(
        XAxiDma_GetRxRing(&AxiDma),
        RX_BD_COUNT_C,
        "RX"
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX completion drain failed\r\n");
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // Invalidate C cache lines before reading results
    //=================================
    user_Invalidate_C_cache();
    

    //=================================
    // Report completion 
    //=================================
    user_Report_Completion();
    

    xil_printf("--- Accelerator main() done ---\r\n");
    return XST_SUCCESS;

}



//=============================================================================
// DMA Initialization
//=============================================================================

static int user_DMA_Init(XAxiDma *AxiDmaPtr) {
    
    XAxiDma_Config *Config;
    int             Status;

    //=================================
    // lookup DMA config
    //=================================
    /* TODO: Modern AMD unified flow uses base address rather than DEVICE_ID. */
    // Config = XAxiDma_LookupConfig(DMA_DEV_ID);
    Config = XAxiDma_LookupConfig(DMA_BASEADDR);
    //-----------------
    if (Config == NULL) {
        xil_printf("No DMA config found for base 0x%08x\r\n", 
            (unsigned int)DMA_BASEADDR);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // initialize DMA driver object
    //=================================
    Status = XAxiDma_CfgInitialize(AxiDmaPtr, Config);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf(
            "XAxiDma_CfgInitialize failed: %d\r\n",
            Status
        );
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // verify SG mode
    //=================================
    if (!XAxiDma_HasSg(AxiDmaPtr)) {
        xil_printf("DMA is not configured in SG mode\r\n");
        //-----------------
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}


//=============================================================================
// TX Ring Setup
//=============================================================================

static int user_Setup_Tx_Ring(XAxiDma *AxiDmaPtr)
{
    XAxiDma_BdRing *TxRingPtr;
    XAxiDma_Bd      BdTemplate;
    u32             BdCount;
    int             Status;

    //=================================
    // get TX ring handle
    //=================================
    TxRingPtr = XAxiDma_GetTxRing(AxiDmaPtr);


    //=================================
    // disable TX interrupts
    //=================================
    XAxiDma_BdRingIntDisable(TxRingPtr, XAXIDMA_IRQ_ALL_MASK);


    //=================================
    // set coalescing policy
    //=================================
    Status = XAxiDma_BdRingSetCoalesce(TxRingPtr, 1, 0);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX coalesce setup failed: %d\r\n", Status);
        return XST_FAILURE;
    }

    //=================================
    // calculate TX ring capacity
    //=================================
    BdCount = XAxiDma_BdRingCntCalc(
        XAXIDMA_BD_MINIMUM_ALIGNMENT,
        TX_BD_SPACE_HIGH - TX_BD_SPACE_BASE + 1U
    );
    //-----------------
    if (BdCount < TX_BD_COUNT_TOTAL) {
        xil_printf(
            "TX BD space too small: have %d need %d\r\n",
            (int)BdCount,
            (int)TX_BD_COUNT_TOTAL
        );
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // create TX ring
    //=================================
    Status = XAxiDma_BdRingCreate(
        TxRingPtr,
        TX_BD_SPACE_BASE,
        TX_BD_SPACE_BASE,
        XAXIDMA_BD_MINIMUM_ALIGNMENT,
        BdCount
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX ring create failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // clear template BD
    //=================================
    XAxiDma_BdClear(&BdTemplate);

    //=================================
    // clone template into TX ring
    //=================================
    Status = XAxiDma_BdRingClone(TxRingPtr, &BdTemplate);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX ring clone failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}


//=============================================================================
// RX Ring Setup
//=============================================================================

static int user_Setup_Rx_Ring(XAxiDma *AxiDmaPtr)
{
    XAxiDma_BdRing *RxRingPtr;
    XAxiDma_Bd      BdTemplate;
    u32             BdCount;
    int             Status;

    //=================================
    // get RX ring handle
    //=================================
    RxRingPtr = XAxiDma_GetRxRing(AxiDmaPtr);


    //=================================
    // disable RX interrupts
    //=================================
    XAxiDma_BdRingIntDisable(RxRingPtr, XAXIDMA_IRQ_ALL_MASK);


    //=================================
    // set coalescing policy
    //=================================
    Status = XAxiDma_BdRingSetCoalesce(RxRingPtr, 1, 0);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX coalesce setup failed: %d\r\n", Status);
        return XST_FAILURE;
    }

    //=================================
    // calculate RX ring capacity
    //=================================
    BdCount = XAxiDma_BdRingCntCalc(
        XAXIDMA_BD_MINIMUM_ALIGNMENT,
        RX_BD_SPACE_HIGH - RX_BD_SPACE_BASE + 1U
    );
    //-----------------
    if (BdCount < RX_BD_COUNT_C) {
        xil_printf(
            "RX BD space too small: have %d need %d\r\n",
            (int)BdCount,
            (int)RX_BD_COUNT_C
        );
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // create RX ring
    //=================================
    Status = XAxiDma_BdRingCreate(
        RxRingPtr,
        RX_BD_SPACE_BASE,
        RX_BD_SPACE_BASE,
        XAXIDMA_BD_MINIMUM_ALIGNMENT,
        BdCount
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX ring create failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // clear template BD
    //=================================
    XAxiDma_BdClear(&BdTemplate);


    //=================================
    // clone template into RX ring
    //=================================
    Status = XAxiDma_BdRingClone(RxRingPtr, &BdTemplate);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX ring clone failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}


//=============================================================================
// UART Initialization
//=============================================================================

static int user_UART_Init(void)
{
    XUartPs_Config *Config;
    int             Status;

    //=================================
    // lookup UART config
    //=================================
    Config = XUartPs_LookupConfig(UART_DEV_ID);
    //-----------------
    if (Config == NULL) {
        xil_printf("UART config lookup failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // initialize UART driver object
    //=================================
    Status = XUartPs_CfgInitialize(
        &UartPs,
        Config,
        Config->BaseAddress
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("UART init failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // set UART baud rate
    //=================================
    Status = XUartPs_SetBaudRate(&UartPs, UART_BAUD_RATE);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("UART baud set failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }

    return XST_SUCCESS;
}


//=============================================================================
// UART Exact Receive
//=============================================================================
/* Blocking receive helper.
   Keeps reading until the requested number of bytes has arrived. */

static int user_UART_Recv_Exact(u8 *Dst, u32 Len){
 
    u32 ReceivedNow;
    u32 TotalReceived;
    u32 IdleTimeOut;

    //=================================
    // initialize receive state
    //=================================
    TotalReceived = 0U;
    IdleTimeOut   = 0U;

    //=================================
    // receive until full payload arrives or timeout expires
    //=================================
    while (TotalReceived < Len) {
        ReceivedNow = XUartPs_Recv(
            &UartPs,
            &Dst[TotalReceived],
            Len - TotalReceived
        );
        //-----------------
        if (ReceivedNow > 0U) {
            TotalReceived += ReceivedNow;
            IdleTimeOut    = 0U;
            continue;
        }
        //-----------------
        if (IdleTimeOut++ >= UART_RECV_TIMEOUT_COUNTER) {
            xil_printf("UART receive timeout: got %u of %u bytes\r\n",
                    (unsigned int)TotalReceived,
                    (unsigned int)Len);
            //-----------------
            return XST_FAILURE;
        }
        //-----------------
        usleep(1U);
    }

    return XST_SUCCESS;
}

//=============================================================================
// Matrix Load From Host
//=============================================================================
/* Receive fixed-size packed A and B from the host through PS UART.

   Expected packet:
   - 16-byte header:
       Magic
       Version
       ABytes
       BBytes
   - A payload
   - B payload

   C is still cleared locally on the target. */

static int user_Load_Matrices_From_Host(void)
{
    user_HostToBoardHdr Hdr;

    u8 *A = (u8 *)MATRIX_A_BASE;
    u8 *B = (u8 *)MATRIX_B_BASE;
    u8 *C = (u8 *)MATRIX_C_BASE;

    int Status;

    //=================================
    // wait for host packet
    //=================================
    xil_printf("Waiting for host matrix packet...\r\n");


    //=================================
    // receive host header
    //=================================
    Status = user_UART_Recv_Exact((u8 *)&Hdr, sizeof(Hdr));
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("Host header receive failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // validate host magic
    //=================================
    if (Hdr.Magic != HOST_TO_BOARD_MAGIC) {
        xil_printf("Bad host magic: 0x%08x\r\n", (unsigned int)Hdr.Magic);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // validate protocol version
    //=================================
    if (Hdr.Version != HOST_PROTO_VERSION) {
    xil_printf("Bad host version: %u\r\n", (unsigned int)Hdr.Version);
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // validate A byte count
    //=================================
    if (Hdr.ABytes != MATRIX_A_BYTES) {
        xil_printf("Bad A byte count: got %u expected %u\r\n",
                (unsigned int)Hdr.ABytes,
                (unsigned int)MATRIX_A_BYTES);
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // validate B byte count
    //=================================
    if (Hdr.BBytes != MATRIX_B_BYTES) {
        xil_printf("Bad B byte count: got %u expected %u\r\n",
                (unsigned int)Hdr.BBytes,
                (unsigned int)MATRIX_B_BYTES);
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // receive packed matrix A
    //=================================
    xil_printf("Receiving packed matrix A...\r\n");
    //-----------------
    Status = user_UART_Recv_Exact(A, MATRIX_A_BYTES);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("A receive failed\r\n");
        //-----------------
        return XST_FAILURE;
    }

    //=================================
    // receive packed matrix B
    //=================================
    xil_printf("Receiving packed matrix B...\r\n");
    //-----------------
    Status = user_UART_Recv_Exact(B, MATRIX_B_BYTES);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("B receive failed\r\n");
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // clear packed matrix C
    //=================================
    memset(C, 0, MATRIX_C_BYTES);


    //=================================
    // report receive completion
    //=================================
    xil_printf("Host matrix receive complete\r\n");

    return XST_SUCCESS;
}


//=============================================================================
// Matrix Load
//=============================================================================

static void user_write_Matrices_To_DDR(void)
{
    u8 *A = (u8 *)MATRIX_A_BASE;
    u8 *B = (u8 *)MATRIX_B_BASE;
    u8 *C = (u8 *)MATRIX_C_BASE;

    u32 i;

    //=================================
    // fill packed matrix A
    //=================================
    for (i = 0U; i < MATRIX_A_BYTES; i++) {
        A[i] = (u8)(i & 0xFFU);
    }


    //=================================
    // fill packed matrix B
    //=================================
    for (i = 0U; i < MATRIX_B_BYTES; i++) {
        B[i] = (u8)((i + 0x55U) & 0xFFU);
    }


    //=================================
    // clear packed matrix C
    //=================================
    memset(C, 0, MATRIX_C_BYTES);
}


//=============================================================================
// Cache Maintenance Before Start
//=============================================================================

static void user_Flush_ABC_Buffers(void)
{
    //=================================
    // flush packed matrix A
    //=================================
    Xil_DCacheFlushRange((UINTPTR)MATRIX_A_BASE, MATRIX_A_BYTES);


    //=================================
    // flush packed matrix B
    //=================================
    Xil_DCacheFlushRange((UINTPTR)MATRIX_B_BASE, MATRIX_B_BYTES);


    //=================================
    // flush packed matrix C
    //=================================
    Xil_DCacheFlushRange((UINTPTR)MATRIX_C_BASE, MATRIX_C_BYTES);
}


//=============================================================================
// RX Descriptor Submission for Matrix C
//=============================================================================

/* Allocate the exact number of RX descriptors
   needed for packed matrix C, attach DDR
   destination addresses, assign lengths, and
   submit them to hardware.

   C is produced by the accelerator and written
   to DDR through the DMA S2MM channel, so these
   descriptors must be posted before start.

   C is treated as one output frame on the RX
   side. RX control is left zero and frame status
   is reported back by hardware. */

   static int user_Submit_Rx_Desc_For_C(XAxiDma *AxiDmaPtr)
{
    XAxiDma_BdRing *RxRingPtr;
    XAxiDma_Bd     *BdPtr;
    XAxiDma_Bd     *BdCurPtr;
    UINTPTR         CurAddr;
    u32             RemainingBytes;
    u32             ChunkLen;
    u32             i;
    int             Status;

    //=================================
    // get RX ring handle
    //=================================
    RxRingPtr = XAxiDma_GetRxRing(AxiDmaPtr);


    //=================================
    // allocate RX descriptors
    //=================================
    Status = XAxiDma_BdRingAlloc(
        RxRingPtr,
        RX_BD_COUNT_C,
        &BdPtr
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX alloc failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // initialize RX descriptor walk state
    //=================================
    BdCurPtr       = BdPtr;
    CurAddr        = (UINTPTR)MATRIX_C_BASE;
    RemainingBytes = MATRIX_C_BYTES;


    //=================================
    // program RX descriptors for C buffer
    //=================================
    for (i = 0U; i < RX_BD_COUNT_C; i++) {
        ChunkLen = (RemainingBytes > BD_TRANSFER_LEN_BYTES) ?
                   BD_TRANSFER_LEN_BYTES : RemainingBytes;


        //=================================
        // set RX buffer address
        //=================================
        Status = XAxiDma_BdSetBufAddr(BdCurPtr, CurAddr);
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "RX set buf addr failed on BD %d\r\n",
                (int)i
            );
            //-----------------
            goto rx_unalloc_allocated_bds;
        }


        //=================================
        // set RX transfer length
        //=================================
        Status = XAxiDma_BdSetLength(
            BdCurPtr,
            ChunkLen,
            RxRingPtr->MaxTransferLen
        );
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "RX set length failed on BD %d\r\n",
                (int)i
            );
            //-----------------
            goto rx_unalloc_allocated_bds;
        }


        //=================================
        // set RX control and software ID
        //=================================
        XAxiDma_BdSetCtrl(BdCurPtr, 0U);
        XAxiDma_BdSetId(BdCurPtr, CurAddr);


        //=================================
        // advance to next RX descriptor
        //=================================
        CurAddr        += ChunkLen;
        RemainingBytes -= ChunkLen;
        //-----------------
        BdCurPtr = (XAxiDma_Bd *)XAxiDma_BdRingNext(
            RxRingPtr,
            BdCurPtr
        );
    }


    //=================================
    // submit RX descriptors to hardware
    //=================================
    Status = XAxiDma_BdRingToHw(
        RxRingPtr,
        RX_BD_COUNT_C,
        BdPtr
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX ToHw failed: %d\r\n", Status);
        //-----------------
        Status = XAxiDma_BdRingUnAlloc(RxRingPtr, RX_BD_COUNT_C, BdPtr);
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf("RX ToHw cleanup unalloc failed: %d\r\n", Status);
        }
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // start RX ring
    //=================================
    Status = XAxiDma_BdRingStart(RxRingPtr);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("RX ring start failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }

    return XST_SUCCESS;

    //=================================
    // error cleanup: unallocate any RX descriptors
    //=================================
    rx_unalloc_allocated_bds:

        Status = XAxiDma_BdRingUnAlloc(
            RxRingPtr,
            RX_BD_COUNT_C,
            BdPtr
        );
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf("RX cleanup unalloc failed: %d\r\n", Status);
        }
        //-----------------
        return XST_FAILURE;

}

//=============================================================================
// TX Descriptor Submission for Matrix A then Matrix B
//=============================================================================
/* Allocate the exact number of TX descriptors
   needed for A and B, then bind them in one
   sequential TX stream.

   Stream order:
   [ A frame ][ B frame ]

   A and B are sent as two separate AXI-Stream
   frames:
   - first TX BD of A -> SOF
   - last  TX BD of A -> EOF
   - first TX BD of B -> SOF
   - last  TX BD of B -> EOF

   If your bridge later changes scheduling, only
   this function should need major edits. */

static int user_Submit_Tx_Desc_For_A_B(XAxiDma *AxiDmaPtr) {

    XAxiDma_BdRing *TxRingPtr;
    XAxiDma_Bd     *BdPtr;
    XAxiDma_Bd     *BdCurPtr;
    UINTPTR         CurAddr;
    u32             RemainingBytes;
    u32             ChunkLen;
    u32             Ctrl;
    u32             aBdIndex;
    u32             bBdIndex;
    int             Status;

    //=================================
    // get TX ring handle
    //=================================
    TxRingPtr = XAxiDma_GetTxRing(AxiDmaPtr);


    //=================================
    // allocate TX descriptors
    //=================================
    Status = XAxiDma_BdRingAlloc(
        TxRingPtr,
        TX_BD_COUNT_TOTAL,
        &BdPtr
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX alloc failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // initialize TX descriptor walk state
    //=================================
    BdCurPtr = BdPtr;


    //=================================
    // program descriptors for matrix A
    //=================================
    /* A is its own AXI-Stream frame:
       - first BD gets SOF
       - last  BD gets EOF */
    CurAddr        = (UINTPTR)MATRIX_A_BASE;
    RemainingBytes = MATRIX_A_BYTES;
    aBdIndex       = 0U;

    while (RemainingBytes != 0U) {
        ChunkLen = (RemainingBytes > BD_TRANSFER_LEN_BYTES) ?
                   BD_TRANSFER_LEN_BYTES : RemainingBytes;

        Ctrl = 0U;
        //-----------------
        if (aBdIndex == 0U) {
            Ctrl |= XAXIDMA_BD_CTRL_TXSOF_MASK;
        }
        //-----------------
        if (aBdIndex == (TX_BD_COUNT_A - 1U)) {
            Ctrl |= XAXIDMA_BD_CTRL_TXEOF_MASK;
        }


        //=================================
        // set A buffer address
        //=================================
        Status = XAxiDma_BdSetBufAddr(BdCurPtr, CurAddr);
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "TX set A buf addr failed on BD %d\r\n",
                (int)aBdIndex
            );
            //-----------------
            goto tx_unalloc_allocated_bds;
        }


        //=================================
        // set A transfer length
        //=================================
        Status = XAxiDma_BdSetLength(
            BdCurPtr,
            ChunkLen,
            TxRingPtr->MaxTransferLen
        );
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "TX set A length failed on BD %d\r\n",
                (int)aBdIndex
            );
            //-----------------
            goto tx_unalloc_allocated_bds;
        }


        //=================================
        // set A control and software ID
        //=================================
        XAxiDma_BdSetCtrl(BdCurPtr, Ctrl);
        XAxiDma_BdSetId(BdCurPtr, CurAddr);


        //=================================
        // advance to next A descriptor
        //=================================
        CurAddr        += ChunkLen;
        RemainingBytes -= ChunkLen;
        aBdIndex++;
        //-----------------
        BdCurPtr = (XAxiDma_Bd *)XAxiDma_BdRingNext(
            TxRingPtr,
            BdCurPtr
        );
    }


    //=================================
    // program descriptors for matrix B
    //=================================
    /* B is its own AXI-Stream frame:
       - first BD gets SOF
       - last  BD gets EOF */
    CurAddr        = (UINTPTR)MATRIX_B_BASE;
    RemainingBytes = MATRIX_B_BYTES;
    bBdIndex       = 0U;

    while (RemainingBytes != 0U) {
        ChunkLen = (RemainingBytes > BD_TRANSFER_LEN_BYTES) ?
                   BD_TRANSFER_LEN_BYTES : RemainingBytes;

        Ctrl = 0U;
        //-----------------
        if (bBdIndex == 0U) {
            Ctrl |= XAXIDMA_BD_CTRL_TXSOF_MASK;
        }
        //-----------------
        if (bBdIndex == (TX_BD_COUNT_B - 1U)) {
            Ctrl |= XAXIDMA_BD_CTRL_TXEOF_MASK;
        }


        //=================================
        // set B buffer address
        //=================================
        Status = XAxiDma_BdSetBufAddr(BdCurPtr, CurAddr);
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "TX set B buf addr failed on BD %d\r\n",
                (int)bBdIndex
            );
            //-----------------
            goto tx_unalloc_allocated_bds;
        }


        //=================================
        // set B transfer length
        //=================================
        Status = XAxiDma_BdSetLength(
            BdCurPtr,
            ChunkLen,
            TxRingPtr->MaxTransferLen
        );
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf(
                "TX set B length failed on BD %d\r\n",
                (int)bBdIndex
            );
            //-----------------
            goto tx_unalloc_allocated_bds;
        }


        //=================================
        // set B control and software ID
        //=================================
        XAxiDma_BdSetCtrl(BdCurPtr, Ctrl);
        XAxiDma_BdSetId(BdCurPtr, CurAddr);


        //=================================
        // advance to next B descriptor
        //=================================
        CurAddr        += ChunkLen;
        RemainingBytes -= ChunkLen;
        bBdIndex++;
        //-----------------
        BdCurPtr = (XAxiDma_Bd *)XAxiDma_BdRingNext(
            TxRingPtr,
            BdCurPtr
        );
    }


    //=================================
    // submit TX descriptors to hardware
    //=================================
    Status = XAxiDma_BdRingToHw(
        TxRingPtr,
        TX_BD_COUNT_TOTAL,
        BdPtr
    );
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX ToHw failed: %d\r\n", Status);
        //-----------------
        Status = XAxiDma_BdRingUnAlloc(TxRingPtr, TX_BD_COUNT_TOTAL, BdPtr);
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf("TX ToHw cleanup unalloc failed: %d\r\n", Status);
        }
        //-----------------
        return XST_FAILURE;
    }


    //=================================
    // start TX ring
    //=================================
    Status = XAxiDma_BdRingStart(TxRingPtr);
    //-----------------
    if (Status != XST_SUCCESS) {
        xil_printf("TX ring start failed: %d\r\n", Status);
        //-----------------
        return XST_FAILURE;
    }
    //-----------------
    return XST_SUCCESS;

    //=================================
    // error cleanup: unallocate any TX BDs that were allocated
    //=================================
    tx_unalloc_allocated_bds:
        Status = XAxiDma_BdRingUnAlloc(
            TxRingPtr,
            TX_BD_COUNT_TOTAL,
            BdPtr
        );
        //-----------------
        if (Status != XST_SUCCESS) {
            xil_printf("TX cleanup unalloc failed: %d\r\n", Status);
        }
        //-----------------
        return XST_FAILURE;
}


//=============================================================================
// Accelerator Programming
//=============================================================================

static void user_Program_Accelerator(void)
{
    //=================================
    // program matrix dimension M
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_M_OFFSET, MATRIX_M);


    //=================================
    // program matrix dimension K
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_K_OFFSET, MATRIX_K);


    //=================================
    // program matrix dimension N
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_N_OFFSET, MATRIX_N);


    //=================================
    // program packed A byte count
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_A_BYTES_OFFSET, MATRIX_A_BYTES);


    //=================================
    // program packed B byte count
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_B_BYTES_OFFSET, MATRIX_B_BYTES);


    //=================================
    // program packed C byte count
    //=================================
    Xil_Out32(ACCEL_BASE_ADDR + ACCEL_REG_C_BYTES_OFFSET, MATRIX_C_BYTES);
}


//=============================================================================
// Accelerator Start
//=============================================================================

/* Assert the start bit once DMA and metadata
   setup is complete.

   This assumes the accelerator accepts a write
   of START=1 as a valid launch event and handles
   its own internal start/status sequencing. */

static void user_Start_Accelerator(void)
{
    //=================================
    // assert accelerator start bit
    //=================================
    Xil_Out32(
        ACCEL_BASE_ADDR + ACCEL_REG_CTRL_OFFSET,
        ACCEL_CTRL_START_MASK
    );
}


//=============================================================================
// Accelerator Done Poll
//=============================================================================
/* Poll the accelerator status register until done, error, or timeout. */

static int user_Wait_For_Done(void)
{
    u32 StatusReg;
    u32 TimeOut;

    //=================================
    // poll accelerator status
    //=================================
    for (TimeOut = 0U; TimeOut < POLL_TIMEOUT_COUNTER; TimeOut++) {
        StatusReg = Xil_In32(
            ACCEL_BASE_ADDR + ACCEL_REG_STATUS_OFFSET
        );


        //=================================
        // check accelerator error bit
        //=================================
        if ((StatusReg & ACCEL_STATUS_ERROR_MASK) != 0U) {
            xil_printf(
                "Accelerator error status: 0x%08x\r\n",
                (unsigned int)StatusReg
            );
            //-----------------
            return XST_FAILURE;
        }


        //=================================
        // check accelerator done bit
        //=================================
        if ((StatusReg & ACCEL_STATUS_DONE_MASK) != 0U) {
            return XST_SUCCESS;
        }

        //-----------------
        usleep(1U);
    }

    xil_printf("Accelerator done timeout\r\n");
    return XST_FAILURE;
}


//=============================================================================
// DMA Completion Drain
//=============================================================================
/* Pull processed descriptors back from hardware
   until the expected count has been reclaimed.

   For every processed BD:
   - verify the BD reports completion
   - verify the BD does not report an error
   - then free the BDs back to the software
     free pool

   This is the required SG cleanup step after
   the hardware side is done. */

   //TODO: are we draining only once at the end to avoid DDR contention?

static int user_Drain_Completed_BDs(
    XAxiDma_BdRing *RingPtr,
    u32             ExpectedBdCount,
    const char     *RingName
){
    XAxiDma_Bd *BdPtr;
    XAxiDma_Bd *BdCurPtr;
    u32         BdSts;
    u32         TotalProcessed;
    int         ProcessedNow;
    int         Status;
    u32         TimeOut;
    int         Index;

    //=================================
    // initialize completion tracking
    //=================================
    TotalProcessed = 0U;
    TimeOut        = 0U;


    //=================================
    // drain completed BDs until expected count is reached
    //=================================
    while (TotalProcessed < ExpectedBdCount) {
        ProcessedNow = XAxiDma_BdRingFromHw(
            RingPtr,
            XAXIDMA_ALL_BDS,
            &BdPtr
        );


        //=================================
        // process returned BDs
        //=================================
        if (ProcessedNow > 0) {
            BdCurPtr = BdPtr;

            //-----------------
            for (Index = 0; Index < ProcessedNow; Index++) {
                BdSts = XAxiDma_BdGetSts(BdCurPtr);


                //=================================
                // check BD error status
                //=================================
                if ((BdSts & XAXIDMA_BD_STS_ALL_ERR_MASK) != 0U) {
                    xil_printf(
                        "%s BD error status: 0x%08x\r\n",
                        RingName,
                        (unsigned int)BdSts
                    );
                    //-----------------
                    XAxiDma_BdRingFree(RingPtr, ProcessedNow, BdPtr);
                    //-----------------
                    return XST_FAILURE;
                }


                //=================================
                // check BD completion status
                //=================================
                if ((BdSts & XAXIDMA_BD_STS_COMPLETE_MASK) == 0U) {
                    xil_printf(
                        "%s BD incomplete status: 0x%08x\r\n",
                        RingName,
                        (unsigned int)BdSts
                    );
                    //-----------------
                    XAxiDma_BdRingFree(RingPtr, ProcessedNow, BdPtr);
                    //-----------------
                    return XST_FAILURE;
                }


                //=================================
                // move to next returned BD
                //=================================
                BdCurPtr = (XAxiDma_Bd *)XAxiDma_BdRingNext(
                    RingPtr,
                    BdCurPtr
                );
            }


            //=================================
            // free processed BDs back to ring
            //=================================
            Status = XAxiDma_BdRingFree(
                RingPtr,
                ProcessedNow,
                BdPtr
            );
            //-----------------
            if (Status != XST_SUCCESS) {
                xil_printf(
                    "%s ring free failed: %d\r\n",
                    RingName,
                    Status
                );
                //-----------------
                return XST_FAILURE;
            }


            //=================================
            // update drain progress
            //=================================
            TotalProcessed += (u32)ProcessedNow;
            TimeOut         = 0U;
            //-----------------
            continue;
        }


        //=================================
        // check drain timeout
        //=================================
        if (TimeOut++ >= POLL_TIMEOUT_COUNTER) {
            xil_printf(
                "%s ring completion timeout\r\n",
                RingName
            );
            //-----------------
            return XST_FAILURE;
        }

        //-----------------
        usleep(1U);
    }

    return XST_SUCCESS;
}


//=============================================================================
// Cache Invalidate for Matrix C
//=============================================================================
/* Invalidate packed matrix C after DMA has written it so the
   CPU reads fresh DDR contents rather than stale cache lines. */

static void user_Invalidate_C_cache(void)
{
    //=================================
    // invalidate packed matrix C
    //=================================
    Xil_DCacheInvalidateRange((UINTPTR)MATRIX_C_BASE, MATRIX_C_BYTES);
}


//=============================================================================
// Completion Report
//=============================================================================
/* This is a placeholder completion report.
   Right now it only prints the base address of
   packed C and the first few bytes.

   Later this can become:
   - UART upload of packed matrix C
   - host response packet
   - correctness check
   - performance counter printout */

static void user_Report_Completion(void)
{
    u8 *C = (u8 *)MATRIX_C_BASE;

    //=================================
    // print job status
    //=================================
    xil_printf("Job complete\r\n");


    //=================================
    // print packed C base address
    //=================================
    xil_printf(
        "Packed matrix C DDR base: 0x%08x\r\n",
        (unsigned int)MATRIX_C_BASE
    );


    //=================================
    // print packed matrix sizes
    //=================================
    xil_printf(
        "Packed matrix sizes: A=%d B=%d C=%d bytes\r\n",
        (int)MATRIX_A_BYTES,
        (int)MATRIX_B_BYTES,
        (int)MATRIX_C_BYTES
    );


    //=================================
    // print first 16 bytes of packed C
    //=================================
    xil_printf("C[0..15] = ");
    //-----------------
    xil_printf(
        "%02x %02x %02x %02x %02x %02x %02x %02x ",
        C[0],
        C[1],
        C[2],
        C[3],
        C[4],
        C[5],
        C[6],
        C[7]
    );
    //-----------------
    xil_printf(
        "%02x %02x %02x %02x %02x %02x %02x %02x\r\n",
        C[8],
        C[9],
        C[10],
        C[11],
        C[12],
        C[13],
        C[14],
        C[15]
    );
}