# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.srcs/sources_1/ip/axi_dma_0/axi_dma_0.xci
# IP: The module: 'axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.srcs/sources_1/ip/axi_dma_0/axi_dma_0.xci
# IP: The module: 'axi_dma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VLSI/Vivado_Projects/edt_zcu102/edt_zcu102.gen/sources_1/ip/axi_dma_0/axi_dma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
